/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BTTuan4;

import com.sun.jndi.ldap.Connection;
import java.sql.*;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import javax.swing.table.AbstractTableModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Khuu Hieu
 */
public class FormSupply extends javax.swing.JFrame {
  /*   static final String url= "jdbc:jtds:sqlserver://localhost:1433/BookSupplier";
     static final String user = "admindb";
    static final String password = "09031999"; */
    /**
     * Creates new form FormSupply
     */
    public FormSupply() {
        
        initComponents();
        loadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        buttonGroupType = new javax.swing.ButtonGroup();
        root = new javax.swing.JPanel();
        tieuDe = new javax.swing.JPanel();
        tieuDeBooks = new javax.swing.JLabel();
        jlbID = new javax.swing.JLabel();
        jlbName = new javax.swing.JLabel();
        jlbType = new javax.swing.JLabel();
        jlbAddr = new javax.swing.JLabel();
        jlbNo = new javax.swing.JLabel();
        jlbEmail = new javax.swing.JLabel();
        jlbRemarks = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtAddr = new javax.swing.JTextField();
        txtNo = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtRemarks = new javax.swing.JTextField();
        jCheckBoxBooks = new javax.swing.JCheckBox();
        jCheckBoxNewspaper = new javax.swing.JCheckBox();
        jCheckBoxJournalMagazine = new javax.swing.JCheckBox();
        jButtonNew = new javax.swing.JButton();
        jButtonSave = new javax.swing.JButton();
        jButtonDel = new javax.swing.JButton();
        jButtonUpdate = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jScrollPaneTbale = new javax.swing.JScrollPane();
        hienThi = new javax.swing.JTable();

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tieuDe.setBackground(new java.awt.Color(0, 51, 51));
        tieuDe.setForeground(new java.awt.Color(0, 102, 102));

        tieuDeBooks.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tieuDeBooks.setText("Books Suppliers");

        javax.swing.GroupLayout tieuDeLayout = new javax.swing.GroupLayout(tieuDe);
        tieuDe.setLayout(tieuDeLayout);
        tieuDeLayout.setHorizontalGroup(
            tieuDeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tieuDeLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tieuDeBooks, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(245, 245, 245))
        );
        tieuDeLayout.setVerticalGroup(
            tieuDeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tieuDeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tieuDeBooks)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jlbID.setText("Supplier ID");

        jlbName.setText("Supplier Name");

        jlbType.setText("Supplier Type");

        jlbAddr.setText("Addr");

        jlbNo.setText("Contact No");

        jlbEmail.setText("Email ID");

        jlbRemarks.setText("Remarks");

        txtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDActionPerformed(evt);
            }
        });

        txtNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNoActionPerformed(evt);
            }
        });

        buttonGroupType.add(jCheckBoxBooks);
        jCheckBoxBooks.setText("Books");

        buttonGroupType.add(jCheckBoxNewspaper);
        jCheckBoxNewspaper.setText("Newspaper");

        buttonGroupType.add(jCheckBoxJournalMagazine);
        jCheckBoxJournalMagazine.setText("Journals and Magazines");

        jButtonNew.setText("New");
        jButtonNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNewActionPerformed(evt);
            }
        });

        jButtonSave.setText("Save");
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });

        jButtonDel.setText("Delete");
        jButtonDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDelActionPerformed(evt);
            }
        });

        jButtonUpdate.setText("Update");
        jButtonUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonUpdateMouseClicked(evt);
            }
        });
        jButtonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateActionPerformed(evt);
            }
        });

        hienThi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "", "ID", "Supplier Name", "Type", "Address", "Contact No", "Email", "Remarks"
            }
        ));
        jScrollPaneTbale.setViewportView(hienThi);

        jScrollPane1.setViewportView(jScrollPaneTbale);

        javax.swing.GroupLayout rootLayout = new javax.swing.GroupLayout(root);
        root.setLayout(rootLayout);
        rootLayout.setHorizontalGroup(
            rootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tieuDe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(rootLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(rootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rootLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jlbID)
                        .addGap(55, 55, 55)
                        .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(509, 509, 509))
                    .addGroup(rootLayout.createSequentialGroup()
                        .addGroup(rootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlbType)
                            .addGroup(rootLayout.createSequentialGroup()
                                .addComponent(jlbName)
                                .addGap(31, 31, 31)
                                .addGroup(rootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(rootLayout.createSequentialGroup()
                                        .addComponent(jCheckBoxBooks)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jCheckBoxNewspaper))
                                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(38, 38, 38)
                                .addComponent(jCheckBoxJournalMagazine))
                            .addGroup(rootLayout.createSequentialGroup()
                                .addGroup(rootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rootLayout.createSequentialGroup()
                                        .addComponent(jlbEmail)
                                        .addGap(61, 61, 61))
                                    .addGroup(rootLayout.createSequentialGroup()
                                        .addGroup(rootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jlbAddr)
                                            .addComponent(jlbNo)
                                            .addComponent(jlbRemarks))
                                        .addGap(45, 45, 45)))
                                .addGroup(rootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtRemarks, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNo, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtAddr, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(rootLayout.createSequentialGroup()
                                .addComponent(jButtonNew)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonSave)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonDel)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonUpdate)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(rootLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 713, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        rootLayout.setVerticalGroup(
            rootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rootLayout.createSequentialGroup()
                .addComponent(tieuDe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(rootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbID)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(rootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbName)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(rootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbType)
                    .addComponent(jCheckBoxBooks)
                    .addComponent(jCheckBoxNewspaper)
                    .addComponent(jCheckBoxJournalMagazine))
                .addGap(18, 18, 18)
                .addGroup(rootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbAddr)
                    .addComponent(txtAddr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(rootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbNo)
                    .addComponent(txtNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(rootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbEmail)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(rootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbRemarks)
                    .addComponent(txtRemarks, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(rootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonUpdate)
                    .addComponent(jButtonDel)
                    .addComponent(jButtonSave)
                    .addComponent(jButtonNew))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(root, javax.swing.GroupLayout.PREFERRED_SIZE, 712, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(root, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDActionPerformed

    private void txtNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNoActionPerformed

    private void jButtonNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNewActionPerformed
            // TODO add your handling code here:
            txtID.setText("");
            txtName.setText("");
            txtAddr.setText("");
            txtNo.setText("");
            txtRemarks.setText("");
            txtEmail.setText("");
            jCheckBoxBooks.setSelected(false);
            jCheckBoxNewspaper.setSelected(false);
            jCheckBoxJournalMagazine.setSelected(false);

            
    }//GEN-LAST:event_jButtonNewActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        loadData();
    }//GEN-LAST:event_formComponentShown
  
    private void loadData(){
        try {
            hienThi.removeAll();
            String[] arr= {"Supplier ID","Supplier Name","Type","Address","Contact No","Email","Remarks"};
            String sql="select * from SupplierForm";
            DefaultTableModel model=new DefaultTableModel(arr,0);
            java.sql.Connection conn = null;
            String url = "jdbc:jtds:sqlserver://localhost:1433/BookSupplier";
            String user = "admindb";
            String password = "09031999";
            conn = DriverManager.getConnection(url, user, password);
            System.out.println(conn);
            PreparedStatement ps=conn.prepareStatement(sql);
            ResultSet rs= ps.executeQuery();
            System.out.println(rs);
            while(rs.next())
            {
                System.out.println(rs.getString(1));
                Vector vector=new Vector();
                vector.add(rs.getString(1));
                vector.add(rs.getString(2));
                vector.add(rs.getString(3));
                vector.add(rs.getString(4));
                vector.add(rs.getString(5));
                vector.add(rs.getString(6));
                vector.add(rs.getString(7));
                model.addRow(vector);
                
            }
            hienThi.setModel(model);
        } catch (SQLException ex) {
            Logger.getLogger(FormSupply.class.getName()).log(Level.SEVERE, null, ex);
        }
         
         
        
    }
    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed
        java.sql.Connection conn = null;
        String url = "jdbc:jtds:sqlserver://localhost:1433/BookSupplier";
        String user = "admindb";
        String password = "09031999";
        String sql= "insert into dbo.SupplierForm" + " VALUES(?, ?, ?, ?, ?, ?, ?)";
        PreparedStatement preStmt = null;
        String strID = txtID.getText();
        String strName = txtName.getText();
        String strType = "";
        String strAddr = txtAddr.getText();
        String strEmail = txtEmail.getText();
        String strSDT = txtNo.getText();
        String strRemark = txtRemarks.getText();
        int row = 0;
      if (jCheckBoxBooks.isSelected()){
        strType = "Books";
      } else {
          if (jCheckBoxNewspaper.isSelected()){
              strType = "Newspaper";
            } else {
              if (jCheckBoxJournalMagazine.isSelected()){
                  strType = "J and M";
              }
          }
      }
       try {
            conn = DriverManager.getConnection(url, user, password);
            preStmt = conn.prepareStatement(sql);
            preStmt.setString(1, strID);
            preStmt.setString(2, strName);
            preStmt.setString(3, strType);
            preStmt.setString(4, strAddr);
            preStmt.setString(5, strSDT);
            preStmt.setString(6, strEmail);
            preStmt.setString(7, strRemark);
            row= preStmt.executeUpdate();
             System.out.println("Row Inserted: " +row);
            conn.close();
        } catch (SQLException ex) {
            Logger.getLogger(FormSupply.class.getName()).log(Level.SEVERE, null, ex);
        }
       loadData();
    }//GEN-LAST:event_jButtonSaveActionPerformed

    private void jButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateActionPerformed
        // TODO add your handling code here:
        java.sql.Connection conn = null;
        String url = "jdbc:jtds:sqlserver://localhost:1433/BookSupplier";
        String user = "admindb";
        String password = "09031999";
        PreparedStatement preStmt = null;
        String strType = "";
         String sql= "update dbo.SupplierForm set SupplierName = "+txtName.getText()+" ,Type = "+strType+" ,Address = "+txtAddr.getText()+" ,ContactNo = "+txtNo.getText()+" ,Email = "+txtEmail.getText()+" ,Remarks = "+txtRemarks.getText()+" where iID = "+txtID.getText();
        if (jCheckBoxBooks.isSelected()){
        strType = "Books";
      } else {
          if (jCheckBoxNewspaper.isSelected()){
              strType = "Newspaper";
            } else {
              if (jCheckBoxJournalMagazine.isSelected()){
                  strType = "J and M";
              }
          }
      }
          try {
            conn = DriverManager.getConnection(url, user, password);
            preStmt = conn.prepareStatement(sql);
             int rows = preStmt.executeUpdate();
             System.out.println("update succeedfull : " + rows );
            conn.close();
        } catch (SQLException ex) {
            Logger.getLogger(FormSupply.class.getName()).log(Level.SEVERE, null, ex);
        }
          loadData();
    }//GEN-LAST:event_jButtonUpdateActionPerformed

    private void jButtonUpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonUpdateMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButtonUpdateMouseClicked

    private void jButtonDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDelActionPerformed
        // TODO add your handling code here:
         java.sql.Connection conn = null;
        String url = "jdbc:jtds:sqlserver://localhost:1433/BookSupplier";
        String user = "admindb";
        String password = "09031999";
        String sql= "delete from dbo.SupplierForm where ID = ? ";
         PreparedStatement preStmt = null;
          try {
            conn = DriverManager.getConnection(url, user, password);
            preStmt = conn.prepareStatement(sql);
            preStmt.setString(1, hienThi.getModel().getValueAt(hienThi.getSelectedRow(), 0).toString());
            preStmt.execute();
            conn.close();
        } catch (SQLException ex) {
            Logger.getLogger(FormSupply.class.getName()).log(Level.SEVERE, null, ex);
        }
          loadData();
    }//GEN-LAST:event_jButtonDelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormSupply.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormSupply.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormSupply.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormSupply.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormSupply().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupType;
    private javax.swing.JTable hienThi;
    private javax.swing.JButton jButtonDel;
    private javax.swing.JButton jButtonNew;
    private javax.swing.JButton jButtonSave;
    private javax.swing.JButton jButtonUpdate;
    private javax.swing.JCheckBox jCheckBoxBooks;
    private javax.swing.JCheckBox jCheckBoxJournalMagazine;
    private javax.swing.JCheckBox jCheckBoxNewspaper;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPaneTbale;
    private javax.swing.JLabel jlbAddr;
    private javax.swing.JLabel jlbEmail;
    private javax.swing.JLabel jlbID;
    private javax.swing.JLabel jlbName;
    private javax.swing.JLabel jlbNo;
    private javax.swing.JLabel jlbRemarks;
    private javax.swing.JLabel jlbType;
    private javax.swing.JPanel root;
    private javax.swing.JPanel tieuDe;
    private javax.swing.JLabel tieuDeBooks;
    private javax.swing.JTextField txtAddr;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtNo;
    private javax.swing.JTextField txtRemarks;
    // End of variables declaration//GEN-END:variables
}
